# Generated by Django 4.0.2 on 2022-05-29 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('basic_street1', models.CharField(blank=True, max_length=80, null=True)),
                ('basic_street2', models.CharField(blank=True, max_length=80, null=True)),
                ('basic_city', models.CharField(blank=True, max_length=40, null=True)),
                ('basic_county', models.CharField(blank=True, max_length=80, null=True)),
                ('basic_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('basic_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
